Models/InfectionReport.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TP1_ARQWEB.Areas.Identity.Data;


namespace TP1_ARQWEB.Models
{


    public class InfectionReport
    {

        public int Id { get; set; }


        [Required]
        public string ApplicationUserId { get; set; }


        [DisplayName("Fecha de diagnóstico")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime DiagnosisDate { get; set; }

        [DisplayName("Fecha de alta")]
        [DataType(DataType.Date)]
        public DateTime? DischargedDate { get; set; }



    }
}

Models/NegativeTest.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TP1_ARQWEB.Areas.Identity.Data;


namespace TP1_ARQWEB.Models
{


    public class NegativeTest
    {

        public int Id { get; set; }


        [Required]
        public string ApplicationUserId { get; set; }


        [DisplayName("Fecha del Test")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime TestDate { get; set; }


    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using TP1_ARQWEB.Data;
using TP1_ARQWEB.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using TP1_ARQWEB.Areas.Identity.Data;
using System.Security.Claims;
using TP1_ARQWEB.Helpers;
using System.Net.Mail;
using TP1_ARQWEB.Mail;
using TP1_ARQWEB.Services;

namespace TP1_ARQWEB.Controllers
{
    public class ReportsController : Controller
    {
        private readonly DBContext _context;
        private readonly IUserInfoManager _userInfoManager;
        private readonly IEmailSender _emailSender;
        private readonly IInfectionService _infectionManager;

        public ReportsController(DBContext context, IUserInfoManager userInfoManager, IEmailSender emailSender, IInfectionService infectionManager)
        {
            _context = context;
            _userInfoManager = userInfoManager;
            _emailSender = emailSender;
            _infectionManager = infectionManager;
        }


        [Authorize]
        public async Task<IActionResult> Details(int id)

        {

            var userIdClaim = UserHelper.getUserId(this);

            if (userIdClaim == null) return NotFound();

            var infectionReport = await _context.InfectionReport
                    .FirstOrDefaultAsync(m => m.ApplicationUserId == userIdClaim && m.Id == id);


            return View(infectionReport);

        }

        // GET: Reports/
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userInfoManager.FindUser(User);

            var infectionReport = await _userInfoManager.GetOpenInfectionReport(currentUser);

            var DiagnosisDate = infectionReport?.DiagnosisDate;

            ReportsIndexViewModel model = new ReportsIndexViewModel
            {
                UserAtRisk = currentUser.AtRisk,
                UserInfected = currentUser.Infected,
                DiagnosisDate = DiagnosisDate
            };

            return View(model);
        }


        [Authorize]
        // GET: Reports/InfectionReport
        public async Task<IActionResult> InfectionReport()
        {
            var currentUser = await _userInfoManager.FindUser(User);

            if (currentUser.Infected)
                return RedirectToAction(nameof(Index));

            return View();
        }


        // POST: Reports/InfectionReport
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> InfectionReport([Bind("Id,DiagnosisDate")] InfectionReport infectionReport)
        {

            var currentUser = await _userInfoManager.FindUser(User);

            try { await _infectionManager.NewInfectionReport(currentUser, infectionReport); }
            catch (ModelException ex)
            {
                ex.UpdateModelState(ModelState);
                return View(infectionReport);
            }

            return RedirectToAction(nameof(Index));

            
        }

        // GET: Reports/Discharge
        [Authorize]
        public async Task<IActionResult> Discharge()
        {
            var currentUser = await _userInfoManager.FindUser(User);
            if (!currentUser.Infected)
                return RedirectToAction(nameof(Index));

            var infectionReport = await _userInfoManager.GetOpenInfectionReport(currentUser);

            if (infectionReport == null)
            {
                return NotFound();
            }

            var infectionDischarge = new InfectionDischarge
            {
                InfectionReportId = infectionReport.Id,
                DiagnosisDate = infectionReport.DiagnosisDate,
                DischargedDate = Time.Now()
            };


            return View(infectionDischarge);
        }

        // POST: Reports/Discharge
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Discharge(InfectionDischarge infectionDischarge)
        {
            var currentUser = await _userInfoManager.FindUser(User);

            try { await _infectionManager.DischargeUser(currentUser, infectionDischarge); }
            catch (ModelException ex)
            {
                ex.UpdateModelState(ModelState);
                return View(infectionDischarge);

            }

            return RedirectToAction("Index", "Home");



        }

        // GET: Reports/NegativeTest
        [Authorize]
        public async Task<IActionResult> NegativeTest()
        {
            var currentUser = await _userInfoManager.FindUser(User);

            if (!currentUser.AtRisk)
                return RedirectToAction(nameof(Index));

            ViewBag.TimeOfLastCondition = currentUser.TimeOfLastCondition;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> NegativeTest([Bind("Id,TestDate")] NegativeTest negativeTest)
        {


            var currentUser = await _userInfoManager.FindUser(User);

            try { await _infectionManager.NewNegativeTest(currentUser, negativeTest); }
            catch (ModelException ex)
            {
                ex.UpdateModelState(ModelState);
                ViewBag.TimeOfLastCondition = currentUser.TimeOfLastCondition;
                return View(negativeTest);
            }

            return RedirectToAction(nameof(Index));
        }


    }


}

Views/Reports/Discharge.cshtml
@model TP1_ARQWEB.Models.InfectionDischarge

@{
    ViewData["Title"] = "Dar de Alta";
}



<h4>Informe de Altá Médica</h4>
<p>Ingrese la fecha para la cual el médico le firmó el alta de la enfermedad.</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Discharge">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DisplayNameFor(m => m.DiagnosisDate)
                @Html.DisplayFor(m => m.DiagnosisDate)
            </div>
            <div class="form-group">
                <label asp-for="DischargedDate" class="control-label"></label>
                <input asp-for="DischargedDate" class="form-control" />
                <asp:CompareValidator ID="cmpDates" runat="server" ControlToValidate="DiagnosisDate"
                                      SetFocusOnError="true" ControlToCompare="DischargedDate"
                                      ErrorMessage="EndDate must be greater than StartDate"
                                      Operator="LessThan"
                                      ValidationGroup="vg" Type="Date"
                                      CultureInvariantValues="true"></asp:CompareValidator>
                <span asp-validation-for="DischargedDate" class="text-danger"></span>


            </div>
            @Html.HiddenFor(m => m.InfectionReportId)
            @Html.HiddenFor(m => m.DiagnosisDate)
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reports/Index.cshtml
@model TP1_ARQWEB.Models.ReportsIndexViewModel

@{
    ViewData["Title"] = "Index";
}

@{
    string disableInfected = "";
    string disableDischarge = "";
    string disableNegativeTest = "";

    string infectionReportClass = "btn-danger";
    string dischargeClass = "btn-primary";
    string negativeTestClass = "btn-primary";

    if (Model.UserInfected)
    {
        disableInfected = "disabled";
        infectionReportClass = "";
    }
    if (!Model.UserInfected)
    {
        disableDischarge = "disabled";
        dischargeClass = "";
    }
    if (!Model.UserAtRisk || Model.UserInfected)
    {
        disableNegativeTest = "disabled";
        negativeTestClass = "";
    }

}

<h4>Reportes</h4>

@if (Model.UserInfected)
{
    <div>
        <p>
            Usted ha informado su contagio; utilizaremos esta información para rastrear a sus contactos.
        </p>
        <hr />
        <dl class="row">

            <dt class="col-sm-4">
                Fecha de Diagnóstico
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DiagnosisDate)
            </dd>
        </dl>
    </div>
}
else if (Model.UserAtRisk)
{
    <p>
        Usted está en riesgo de haber sido contagiado. En lo posible, realice un Test de Coronavirus y, en caso de resultar negativo, infórmelo.
    </p>
} else
{
    <p>Usted está actualmente en condiciones normales.</p>
}

<div class="btn-group-vertical">

    <input style="margin-bottom:14px" class="btn  @infectionReportClass" type="button" value="Reportar Contagio" onclick="location.href='@Url.Action("InfectionReport", "Reports")'" @disableInfected />
    <input style="margin-bottom:14px" class="btn  @dischargeClass" type="button" value="Reportar Alta" onclick="location.href='@Url.Action("Discharge", "Reports")'" @disableDischarge />
    <input style="margin-bottom:14px" class="btn  @negativeTestClass" type="button" value="Reportar Test Negativo" onclick="location.href='@Url.Action("NegativeTest", "Reports")'" @disableNegativeTest />

</div>

Views/Reports/InfectionReport.cshtml
@model TP1_ARQWEB.Models.InfectionReport

@{
    ViewData["Title"] = "Informar contagio";
}




<h4>Reporte de infección</h4>
<p>Utilizaremos estos datos para rastrear a sus contactos</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="InfectionReport">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DiagnosisDate" class="control-label"></label>
                <input asp-for="DiagnosisDate" class="form-control" />

                <span asp-validation-for="DiagnosisDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reports/NegativeTest.cshtml
@model TP1_ARQWEB.Models.NegativeTest

@{
    ViewData["Title"] = "Informar test negativo";
    var dateToShow = ViewBag.TimeOfLastCondition.ToString("dd/MM/yyyy");
}




<h4>Reporte de Test con resultado Negativo</h4>
<p>Usted fue puesto en riesgo por última vez el @dateToShow.</p>
<p>Por favor introduzca la fecha en que COMENZÓ su test, no la fecha en que recibió los resultados.</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NegativeTest">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TestDate" class="control-label"></label>
                <input asp-for="TestDate" class="form-control" />

                <span asp-validation-for="TestDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}