Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TP1_ARQWEB.Models;
using Microsoft.EntityFrameworkCore;
using TP1_ARQWEB.Areas.Identity.Data;
using TP1_ARQWEB.Data;
using TP1_ARQWEB.Services;

namespace TP1_ARQWEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        
        private readonly DBContext _context;

        private UsuariosYLocs _repoUsers;

        public AdministratorController(
           UserManager<ApplicationUser> userManager, DBContext context)
        {
            _userManager = userManager;
            _context = context;
            _repoUsers = new UsuariosYLocs();
        }

        public IActionResult Index()
        { 
             
            return View();
        }
        public IActionResult DataUsers()
        {


            var model = new AdministratorViewModel
            {
                Propietarios = _repoUsers.usuariosPropietarios(_context),
                
            };
            return View(model);

            
        }
        
    }
}

Views/Shared/_AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TP1_ARQWEB.Models
@using Microsoft.AspNetCore.Authorization;
@using TP1_ARQWEB.Areas.Identity.Data;



@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

@if (signInManager.IsSignedIn(User))
{
    var currentUser = await userManager.GetUserAsync(User);
    var isAdmin = currentUser != null
        && await userManager.IsInRoleAsync(
            currentUser,
            "Admin");
    if (isAdmin)
    {
        @*<ul class="nav navbar-nav navbar-right">*@
        <ul class="myclase navbar-nav">
            

            <li class=" nav-item">
                <a id="locat" class="nav-link  text-dark" asp-controller="Administrator"
                   asp-action="Index">
                    Administrador
                </a>
            </li>
        </ul>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP1_ARQWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">*@
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        
       <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom   border-bottom box-shadow mb-3">
       

        <div class="container">

            <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index"> <img src="/images/logowhite.svg"></a>


            <button type="button" class="navbar-toggler navbar-light" style="background-color: white" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbarCollapse" class=" navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial.cshtml" />
                <partial name="_AdminActionsPartial" />
            </div>
        </div>
        </nav>
    </header>
  
<div class="container paddingClase">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CovidWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Nosotros</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>