Models/Location.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TP1_ARQWEB.Services;

namespace TP1_ARQWEB.Models
{
    public class GeneralizedLocation
    {

        public string name { get; set; }
        public int concurrence { get; set; }
        public int capacity { get; set; }

        public double latitude { get; set; }
        public double longitude { get; set; }

        public ExternalLocation ToExtLocation(int id)
        {
            return new ExternalLocation
            {
                Nombre = name,
                CantidadPersonasDentro = concurrence,
                Capacidad = capacity,
                Latitud = latitude,
                Longitud = longitude,
                Id = id
            };
        }

    }
    public class Location
    {
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        public string IdPropietario { get; set; }

        [Required]
        public int Capacidad { get; set; }

        [Required]
        public double Latitud { get; set; }
        [Required]
        public double Longitud { get; set; }
        public int CantidadPersonasDentro { get; set; }
        public byte[] Image { get; set; }

        [Required]
        public int AperturaHora { get; set; }
        [Required]
        public int AperturaMinuto { get; set; }
        [Required]
        public int CierreHora { get; set; }
        [Required]
        public int CierreMinuto { get; set; }

        public bool AbreATodaHora()
        {
            return AperturaHora == CierreHora && AperturaMinuto == CierreMinuto;
        }

        public bool AbreAMedianoche()
        {
            return AperturaHora > CierreHora
                || (AperturaHora == CierreHora && AperturaMinuto >= CierreMinuto);
        }

        public bool Abierto()
        {

            var horaActual = Time.Now().Hour;
            var minutoActual = Time.Now().Minute;

            if (AbreATodaHora()) return true;

            bool despuesDeApertura = horaActual > AperturaHora
                || horaActual == AperturaHora && minutoActual >= AperturaMinuto;
            bool antesDeCierre = horaActual < CierreHora
                || horaActual == CierreHora && minutoActual < CierreMinuto;

            if (AbreAMedianoche()) return despuesDeApertura || antesDeCierre;
            else return despuesDeApertura && antesDeCierre;

        }

        public virtual bool TieneHorario()
        {
            return true;
        }

        [Timestamp]
        public byte[] RowVersion { get; set; }

    }

    public class ExternalLocation : Location
    {
        public override bool TieneHorario()
        {
            return false;
        }
    }
}

Models/ViewModels/ImageViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP1_ARQWEB.Models
{
    public class ImageViewModel
    {
        public string ImageName { get; set; }
        public long ImageSize { get; set; }

        public Location CurrentLocation { get; set; }

    }
}

Models/ViewModels/QRCodeViewModel.cs
using System;

namespace TP1_ARQWEB.Models
{
    public class QRCodeViewModel
    {
        public Location location { get; set; }
        
        public string QREncodedBase64 { get; set; }
    }
}

Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TP1_ARQWEB.Data;
using TP1_ARQWEB.Models;

namespace TP1_ARQWEB.Controllers
{
    public class ImageController : Controller
    {

        private readonly DBContext _context;
        public ImageController(DBContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> ShowLocationImage(int id)
        {
            var location = await _context.Location.FindAsync(id);

            var imageData = location.Image;

            return File(imageData, "image/jpg");
        }
    }
}

Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP1_ARQWEB.Data;
using TP1_ARQWEB.Models;
using Microsoft.AspNetCore.Identity;
using TP1_ARQWEB.Areas.Identity.Data;
using Microsoft.AspNetCore.Http;
using QRCoder;
using TP1_ARQWEB.Services;

namespace TP1_ARQWEB.Controllers
{
    public class LocationsController : Controller
    {
        private readonly DBContext _context;
        private readonly IUserInfoManager _userInfoManager;
        private readonly ILocationService _locationService;
        private readonly UserManager<ApplicationUser> _userManager;


        public LocationsController(UserManager<ApplicationUser> userManager, DBContext context, IUserInfoManager userInfoManager, ILocationService locationService)
        {
            _userManager = userManager;
            _userInfoManager = userInfoManager;
            _context = context;
            _locationService = locationService;
        }

        private ApplicationUser currentUser;
        private Location location;

        private async Task UpdateUserAndLocation(int? idLocation)
        {
            currentUser = await _userInfoManager.FindUser(User);
            location = await _locationService.GetLocationById(idLocation);
            _locationService.AssertOwnership(location, currentUser);
        }

        // GET: Locations
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userInfoManager.FindUser(User);
            return View(_locationService.GetLocationsForUser(currentUser));
        }

        // GET: Locations/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {

            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }
            

            return View(location);
        }

        // GET: Locations/QRCode/5
        [Authorize]
        public async Task<IActionResult> QRCode(int? id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            var qrCodeImageAsBase64 = _locationService.GetQrCode(location);

            var model = new QRCodeViewModel()
            {
                QREncodedBase64 = qrCodeImageAsBase64,
                location = location
            };

            return View(model);
        }

        // GET: Locations/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Nombre,IdPropietario,Capacidad,Latitud,Longitud,AperturaHora,AperturaMinuto,CierreHora,CierreMinuto")] Location location)
        {

            var currentUser = await _userInfoManager.FindUser(User);

            try { await _locationService.CreateNewLocation(location, currentUser); }
            catch ( ModelException ex )
            {
                ex.UpdateModelState(ModelState);
                return View(location);
            }

            return RedirectToAction(nameof(Index));

        }

        // GET: Locations/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            var model = location; 
            
            return View(model);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Nombre,Capacidad,Latitud,Longitud,AperturaHora,AperturaMinuto,CierreHora,CierreMinuto")] Location model)
        {

            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            try { await _locationService.EditLocation(location, model); }
            catch (ModelException ex)
            {
                ex.UpdateModelState(ModelState);
                return View(model);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Locations/Image/5
        [Authorize]
        public async Task<IActionResult> Image(int? id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            ImageViewModel model = new ImageViewModel
            {
                CurrentLocation = location
            };

            return View(model);
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Image(int? id, IFormFile file)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }



            try { await _locationService.UpdateImage(location, file); }
            catch (ModelException ex)
            {
                ex.UpdateModelState(ModelState);
                ImageViewModel model = new ImageViewModel
                {
                    CurrentLocation = location
                };

                if (file != null)
                {
                    model.ImageName = file.Name;
                    model.ImageSize = file.Length;
                }

                return View(model);
            }

            return RedirectToAction(nameof(Image));
        }


        

        // GET: Locations/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            return View(location);
            
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            await _locationService.RemoveLocation(location);

            return RedirectToAction(nameof(Index));
        }

        

        // POST: Locations/DeleteImage/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteImage(int id)
        {
            try { await UpdateUserAndLocation(id); }
            catch { return NotFound(); }

            await _locationService.RemoveImage(location);

            return RedirectToAction(nameof(Image), new {id = id });
        }
    }
}

Views/Locations/Create.cshtml
@model TP1_ARQWEB.Models.Location

@{
    ViewData["Title"] = "Crear locación";
}

<h1>Agregar locación</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacidad" class="control-label"></label>
                <input asp-for="Capacidad" class="form-control" />
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Latitud" class="control-label"></label>
                        <input asp-for="Latitud" class="form-control" />
                        <span asp-validation-for="Latitud" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Longitud" class="control-label"></label>
                        <input asp-for="Longitud" class="form-control" />
                        <span asp-validation-for="Longitud" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Horario de Apertura</label>
                <div class="input-group">
                    <input asp-for="AperturaHora" class="form-control" />
                    <span class="input-group-text">h</span>
                    <input asp-for="AperturaMinuto" class="form-control" />
                    <span class="input-group-text">m</span>
                </div>
                <span asp-validation-for="AperturaHora" class="text-danger"></span>
                <span asp-validation-for="AperturaMinuto" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Horario de Cierre</label>
                <div class="input-group">
                    <input asp-for="CierreHora" class="form-control" />
                    <span class="input-group-text">h</span>
                    <input asp-for="CierreMinuto" class="form-control" />
                    <span class="input-group-text">m</span>
                </div>
                <span asp-validation-for="CierreHora" class="text-danger"></span>
                <span asp-validation-for="CierreMinuto" class="text-danger"></span>
            </div>



            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Locations/Delete.cshtml
@model TP1_ARQWEB.Models.Location

@{
    ViewData["Title"] = "Borrar";
}

<h1>Borrar</h1>

<h3>¿Estás seguro de que querés borrarlo?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitud)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitud)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitud)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitud)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

Views/Locations/Details.cshtml
@model TP1_ARQWEB.Models.Location

@{
    ViewData["Title"] = "Detalles";
}

@{ 
    var HorarioApertura = new DateTime(1, 1, 1, Model.AperturaHora, Model.AperturaMinuto, 0);
    var HorarioCierre = new DateTime(1, 1, 1, Model.CierreHora, Model.CierreMinuto, 0);
}

<h1>Detalles</h1>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidad)
        </dd>
        <dt class="col-sm-2">
            Horario de Apertura
        </dt>
        <dd class="col-sm-10">
            @HorarioApertura.ToString("HH:mm")
        </dd>
        <dt class="col-sm-2">
            Horario de Cierre
        </dt>
        <dd class="col-sm-10">
            @HorarioCierre.ToString("HH:mm")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitud)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitud)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitud)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitud)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

Views/Locations/Edit.cshtml
@model TP1_ARQWEB.Models.Location

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar locación</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacidad" class="control-label"></label>
                <input asp-for="Capacidad" class="form-control" />
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitud" class="control-label"></label>
                <input asp-for="Latitud" class="form-control" />
                <span asp-validation-for="Latitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitud" class="control-label"></label>
                <input asp-for="Longitud" class="form-control" />
                <span asp-validation-for="Longitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Horario de Apertura</label>
                <div class="input-group">
                    <input asp-for="AperturaHora" class="form-control" />
                    <span class="input-group-text">h</span>
                    <input asp-for="AperturaMinuto" class="form-control" />
                    <span class="input-group-text">m</span>
                </div>
                <span asp-validation-for="AperturaHora" class="text-danger"></span>
                <span asp-validation-for="AperturaMinuto" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Horario de Cierre</label>
                <div class="input-group">
                    <input asp-for="CierreHora" class="form-control" />
                    <span class="input-group-text">h</span>
                    <input asp-for="CierreMinuto" class="form-control" />
                    <span class="input-group-text">m</span>
                </div>
                <span asp-validation-for="CierreHora" class="text-danger"></span>
                <span asp-validation-for="CierreMinuto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Locations/Image.cshtml
@model TP1_ARQWEB.Models.ImageViewModel

@{
    ViewData["Title"] = "Imágen";
}


<h1>Imágen</h1>


@if (Model.CurrentLocation.Image != null)
{
    <img class="location-image" src='@Url.Action("ShowLocationImage", "Image", new { id = Model.CurrentLocation.Id })' width="500" />
}

@using (Html.BeginForm("Image", "Locations", FormMethod.Post,
                      new { enctype = "multipart/form-data" }))
{
    <label for="file">Subir imágen:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />
    @Html.HiddenFor(m => m.CurrentLocation)

    <input type="submit" value="Subir" class="submit" />
    <br />
    <span asp-validation-for="ImageName" class="text-danger"></span>
    <span asp-validation-for="ImageSize" class="text-danger"></span>

}

@if (Model.CurrentLocation.Image != null)
{
    <form asp-action="DeleteImage" asp-route-id="@Model.CurrentLocation.Id">
        <input type="submit" value="Borrar" class="submit" />
    </form>
}

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Locations/Index.cshtml
@model IEnumerable<TP1_ARQWEB.Models.Location>
@using System.Security.Claims;
@{
    ViewData["Title"] = "Index";
    var claimsIdentity = User.Identity as ClaimsIdentity;
}

<h1>Tabla de locaciones</h1>

<p>
    <a asp-action="Create">Agregar locacion</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitud)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitud)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Image" asp-route-id="@item.Id">Imágen</a> |
                <a asp-action="QRCode" asp-route-id="@item.Id">Código QR</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
                    

                
            

        }
    </tbody>
</table>

Views/Locations/QRCode.cshtml
@model TP1_ARQWEB.Models.QRCodeViewModel


@{
    ViewData["Title"] = "Código QR";
}



<div>
    <h1>@Html.DisplayFor(model => model.location.Nombre)</h1>
    <hr />

    <img src="data:image/png;base64, @Model.QREncodedBase64" width="950" height="950"/>
</div>
<div>
    <a asp-action="Index">Volver a la lista</a>
</div>